{{- if .Values.jellyfin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-server.fullname" . }}-jellyfin
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: jellyfin
  {{- with .Values.jellyfin.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.jellyfin.service.type }}
  ports:
  - port: {{ .Values.jellyfin.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  - port: 8920
    targetPort: https
    protocol: TCP
    name: https
  - port: 7359
    targetPort: discovery
    protocol: UDP
    name: discovery
  - port: 1900
    targetPort: dlna
    protocol: UDP
    name: dlna
  selector:
    {{- include "media-server.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jellyfin
{{- end }}
