apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-chart
  namespace: argocd
spec:
  project: team-alpha
  source:
    repoURL: https://github.com/DramisInfo/platform-tools
    targetRevision: HEAD
    path: app-teams/team-alpha/charts/demo-chart
    helm:
      values: |
        replicaCount: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: team-alpha-demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
