apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: team-alpha
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.*
    chart: podinfo
    helm:
      values: |
        replicaCount: 2
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: team-alpha-demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
