apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - collector-config.yaml
  - deployment.yaml
  - service.yaml
  # ServiceMonitor requires Prometheus Operator CRDs - using regular Prometheus scraping instead
  # - servicemonitor.yaml
