apiVersion: v1
kind: Service
metadata:
  name: otel-github-collector
  namespace: monitoring
  labels:
    app: otel-github-collector
spec:
  ports:
    - name: metrics
      port: 8888
      targetPort: 8888
  selector:
    app: otel-github-collector
