apiVersion: v1
kind: Service
metadata:
  name: otel-github-collector
  namespace: monitoring
  labels:
    app: otel-github-collector
spec:
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
  selector:
    app: otel-github-collector
