replicaCount: 2

image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: "6.9.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9898

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prd
  host: pi.cace-1-dev.dramisinfo.com
  tls:
    enabled: true
    secretName: podinfo-tls

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

postgres:
  enabled: true
  instances: 2
  image: ghcr.io/cloudnative-pg/postgresql:16
  database: demo_app
  username: demo_user
  password: changeme123
  storage:
    size: 1Gi
    storageClass: local-path
  monitoring:
    enabled: true
    enablePodMonitor: true
  parameters:
    maxConnections: "100"
    sharedBuffers: 256MB
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
